export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_CONTINETS = "GET_CONTINETS";
export const CLEAR_COUNTRY = "CLEAR_COUNTRY";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const FILTER_CONTINENTS = "FILTER_CONTINENTS";
export const FILTER_ACTIVITIES = "FILTER_ACTIVITIES";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";

// y esta la de post 

