export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const ORDER_COUNTRIES = 'ORDER_COUNTRIES';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const EMPTY_COUNTRY_DETAILS = 'EMPTY_COUNTRY_DETAILS';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const FILTER_BY_POPULATION = 'FILTER_BY_POPULATION';
export const FILTER_BY_AREA = 'FILTER_BY_AREA';

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const FILTER_BY_DIFFICULTY = 'FILTER_BY_DIFFICULTY';
export const FILTER_BY_SEASSON = 'FILTER_BY_SEASSON';
export const GET_ACTIVITY_DETAILS = 'GET_ACTIVITY_DETAILS';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';

    
     
    
    
    

    